using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Manus.ToBeHermes.Skeleton
{
	public enum BoneType
	{
		Unknown = -1,
		Root = 0,
		Head = 1,
		Neck = 2,
		Hips = 3,
		Spine = 4,
		Chest = 5,
		UpperChest = 6, 
		LeftUpperLeg = 7,
		RightUpperLeg = 8,
		LeftLowerLeg = 9,
		RightLowerLeg = 10,
		LeftFoot = 11,
		RightFoot = 12,
		LeftToes = 13,
		RightToes = 14,
		LeftToesEnd = 15,
		RightToesEnd = 16,
		LeftShoulder = 17,
		RightShoulder = 18,
		LeftUpperArm = 19,
		RightUpperArm = 20,
		LeftLowerArm = 21,
		RightLowerArm = 22,
		LeftHand = 23,
		RightHand = 24,

		LeftThumbProximal = 50,
		LeftThumbMiddle = 51,
		LeftThumbDistal = 52,
		LeftThumbTip = 53,
		RightThumbProximal = 54,
		RightThumbMiddle = 55,
		RightThumbDistal = 56,
		RightThumbTip = 57,
		LeftIndexProximal = 58,
		LeftIndexMiddle = 59,
		LeftIndexDistal = 60,
		LeftIndexTip = 61,
		RightIndexProximal = 62,
		RightIndexMiddle = 63,
		RightIndexDistal = 64,
		RightIndexTip = 65,
		LeftMiddleProximal = 66,
		LeftMiddleMiddle = 67,
		LeftMiddleDistal = 68,
		LeftMiddleTip = 69,
		RightMiddleProximal = 70,
		RightMiddleMiddle = 71,
		RightMiddleDistal = 72,
		RightMiddleTip = 73,
		LeftRingProximal = 74,
		LeftRingMiddle = 75,
		LeftRingDistal = 76,
		LeftRingTip = 77,
		RightRingProximal = 78,
		RightRingMiddle = 79,
		RightRingDistal = 80,
		RightRingTip = 81,
		LeftPinkyProximal = 82,
		LeftPinkyMiddle = 83,
		LeftPinkyDistal = 84,
		LeftPinkyTip = 85,
		RightPinkyProximal = 86,
		RightPinkyMiddle = 87,
		RightPinkyDistal = 88,
		RightPinkyTip = 89,
	}
}